### PR TITLE
Quote environmental variables values

### PR DESCRIPTION
**Pull request by furushchev**
Without quoting the paths, It can occur word splitting issue.
https://github.com/koalaman/shellcheck/wiki/SC2086

When a path in `PATH` or `LD_LIBRARY_PATH` contains whitespace, it stops parsing the values on the whitespace.

How to reproduce the error:

```
apt install ros-melodic-jskeus
export PATH="/var/A B/bin:$PATH"  # "A B" contains a whitespace
# Any commands with env.sh fails on the error
source /opt/ros/melodic/env.sh rostopic list
```

### CODE REVIEW

**Comment by furushchev** [comment]
It looks some tests fail on some errors not related to this change.
@k-okada Could you help with solving this?

**Comment by k-okada** [comment]
update default branch to `release/melodic/euslisp` this should be ok.

**Comment by furushchev** [comment]
> update default branch to `release/melodic/euslisp` this should be ok.

Done!

**Comment by furushchev** [comment]
(Kindly ping to maintainer @k-okada )

**Comment by k-okada** [comment]
travis still failing , any idea?

**Comment by furushchev** [comment]
@k-okada Briefly checking logs, multiple errors found as below:

https://travis-ci.org/github/tork-a/euslisp-release/jobs/766734683
https://travis-ci.org/github/tork-a/euslisp-release/jobs/766734685

```
docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

It looks you pulled docker image hosted on DockerHub too many times without logged in by any account.
Since 2020/11 (AFAIR) the error may occurs if you pull images many times without logging in to any account.

---

https://travis-ci.org/github/tork-a/euslisp-release/jobs/766734696

It looks using `sudo` command on docker iamge without `sudo` installed?

---

https://travis-ci.org/github/tork-a/euslisp-release/jobs/766734686#L7069

qemu crashed on some test programs. I'm not sure where does the error come from...

---

https://travis-ci.org/github/tork-a/euslisp-release/jobs/766734687#L6614-L6615

Test program exited on segmentation fault. Maybe restarting the test resolves the issue?

--- 

https://travis-ci.org/github/tork-a/euslisp-release/jobs/766734688

It exceeded its time limit.. (maybe restart?)

**Pull request merged**
